when:
  event: [push, pull_request, manual]

steps:
  tofu-plan:
    image: ghcr.io/opentofu/opentofu:1.12
    commands:
      - tofu init
      - tofu plan
    environment:
      VAULT_ADDR: http://k8s-openbao.openbao.svc:8200
      VAULT_TOKEN:
        from_secret: vault_root_token
    backend_options:
      kubernetes:
        secrets:
          - name: gh-org-github-token
            key: tofu_state_access_key_id
            target:
              env: AWS_ACCESS_KEY_ID
          - name: gh-org-github-token
            key: tofu_state_secret_access_key
            target:
              env: AWS_SECRET_ACCESS_KEY

  tofu-apply:
    image: ghcr.io/opentofu/opentofu:1.12
    commands:
      - tofu init
      - tofu apply -auto-approve
    environment:
      VAULT_ADDR: http://k8s-openbao.openbao.svc:8200
      VAULT_TOKEN:
        from_secret: vault_root_token
    when:
      branch: main
      event: push
    backend_options:
      kubernetes:
        secrets:
          - name: gh-org-github-token
            key: tofu_state_access_key_id
            target:
              env: AWS_ACCESS_KEY_ID
          - name: gh-org-github-token
            key: tofu_state_secret_access_key
            target:
              env: AWS_SECRET_ACCESS_KEY
